version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
# version: '3.1'
# services:
#   gift.api:
#     image: gift-api:latest
#     container_name: api
#     restart: always
#     ports:
#       - 8000:8000
#     volumes:
#       - ./.env:/opt/app/.env
